# Generated by Django 4.0 on 2022-01-06 10:03

import apis.nft_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favouritenft',
            name='is_removed',
        ),
        migrations.AddField(
            model_name='favouritenft',
            name='is_favorite',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='banner_image',
            field=models.ImageField(upload_to=apis.nft_management.models.upload_to),
        ),
        migrations.AlterField(
            model_name='collection',
            name='logo_image',
            field=models.ImageField(upload_to=apis.nft_management.models.upload_to),
        ),
        migrations.AlterField(
            model_name='nft',
            name='image',
            field=models.ImageField(upload_to=apis.nft_management.models.upload_to),
        ),
    ]
