# Generated by Django 4.0.1 on 2022-01-06 06:56

import apis.nft_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='banner_image',
            field=models.ImageField(upload_to=apis.nft_management.models.upload_to),
        ),
        migrations.AlterField(
            model_name='collection',
            name='logo_image',
            field=models.ImageField(upload_to=apis.nft_management.models.upload_to),
        ),
        migrations.AlterField(
            model_name='nft',
            name='image',
            field=models.ImageField(upload_to=apis.nft_management.models.upload_to),
        ),
    ]
