# Generated by Django 4.0 on 2022-01-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft_management', '0002_remove_favouritenft_is_removed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportednft',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
