# Generated by Django 4.0 on 2022-01-10 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nft_management', '0003_reportednft_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ('id',)},
        ),
    ]
