# Generated by Django 4.0 on 2022-01-11 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_is_removed'),
        ('nft_management', '0004_alter_collection_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_collection', to='accounts.user'),
        ),
    ]
