# Generated by Django 4.0 on 2022-01-11 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nft_management', '0002_alter_collection_banner_image_and_more'),
        ('nft_management', '0005_alter_collection_user'),
    ]

    operations = [
    ]
