# Generated by Django 4.0 on 2022-01-12 10:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_about_profile_banner_image'),
        ('nft_management', '0006_merge_20220111_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='nft',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='nft',
            unique_together={('name', 'owner')},
        ),
    ]
