# Generated by Django 4.0 on 2021-12-30 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nft_management', '0001_initial'),
        ('accounts', '__first__'),
        ('bidding_and_transection', '0002_initial'),
        ('wallet_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfttransaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_wallet', to='wallet_management.wallet'),
        ),
        migrations.AddField(
            model_name='bidding',
            name='nft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidding_nft', to='nft_management.nft'),
        ),
        migrations.AddField(
            model_name='bidding',
            name='offer_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_biding', to='accounts.user'),
        ),
    ]
