# Generated by Django 4.0 on 2022-01-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
