# Generated by Django 4.0 on 2022-01-11 11:20

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_is_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='banner_image',
            field=models.ImageField(default='posts/default.jpg', upload_to=accounts.models.upload_to, verbose_name='bannner_Image'),
        ),
    ]
