# Generated by Django 4.0 on 2022-01-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_address',
            field=models.TextField(),
        ),
    ]
