# Generated by Django 4.0 on 2021-12-30 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nft_management', '0001_initial'),
        ('accounts', '__first__'),
        ('admin_site_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nft_management.category'),
        ),
        migrations.AddField(
            model_name='faq',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FAQ_user', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='contact',
            name='resolved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolved_user', to='accounts.user'),
        ),
    ]
