# Generated by Django 4.0.1 on 2022-01-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site_management', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
