# Generated by Django 4.0 on 2022-01-11 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_about_profile_banner_image'),
        ('admin_site_management', '0003_alter_contact_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolved_user', to='accounts.user'),
        ),
    ]
